I solved the above issues

diff --git a/scripts/gitlines b/scripts/gitlines
--- a/scripts/gitlines
+++ b/scripts/gitlines
@@ -2,3 +2,24 @@
 
 # TODO: Display lines of code by language in a remote git repository
 # Refer "cloc" command or similar
+
+if [[ $# -ne 1 ]]; then
+    echo "Usage: $0 <repo_url>"
+    exit 1
+fi
+
+repo=$1
+temp=$(mktemp -d)
+
+echo "Cloning repository: $repo..."
+git clone --depth 1 "$repo" "$temp" >/dev/null 2>&1
+
+if [[ $? -ne 0 ]]; then
+    echo "Failed to clone repository."
+    exit 1
+fi
+
+echo "Analyzing lines of code."
+cloc "$temp"
+
+rm -rf "$temp"
diff --git a/scripts/music-extract b/scripts/music-extract
--- a/scripts/music-extract
+++ b/scripts/music-extract
@@ -26,3 +26,41 @@
 # └── Songs
 #     ├── Song1.mp3
 #     └── Song2.mp3
+
+#!/usr/bin/env bash
+
+if [ $# -ne 1 ]; then
+    echo "Usage: $0 <source_folder>"
+    exit 1
+fi
+
+src=$(realpath "$1")
+
+if [ ! -d "$src" ]; then
+    echo "Error: Source folder '$src' does not exist."
+    exit 1
+fi
+
+command -v ffmpeg >/dev/null 2>&1 || { echo "Error: ffmpeg is not installed."; exit 1; }
+
+head=$(dirname "$src")
+output="$head/Music"
+
+echo "Source folder: $src"
+echo "Output folder: $out"
+
+
+find "$src" -type f -iname "*.mp4" | while IFS= read -r input; do
+    
+    path="${input#$src/}"
+    new="${path%.mp4}.mp3"
+    final="$output/$new"
+
+    mkdir -p "$(dirname "$final")"
+    echo "Converting '$input' → '$final'..."
+
+    ffmpeg -i "$input" -q:a 2 -acodec libmp3lame -vn "$final" -y
+done
+
+echo "All mp3 files saved in '$output'."
+
diff --git a/scripts/perms b/scripts/perms
--- a/scripts/perms
+++ b/scripts/perms
@@ -7,3 +7,15 @@
 # 775 weather
 # 664 ../README.md
 
+#!/usr/bin/env bash
+
+if [[ $# -eq 0 ]]; then
+    echo "Usage: $0 <file1> <file2> ..."
+    exit 1
+fi
+
+for file in "$@"; do
+    [[ -e "$file" ]] || { echo "File not found: $file"; continue; }
+    perms=$(stat -c "%a" "$file")
+    echo "$perms $file"
+done
