writing perm script

diff --git a/scripts/perms b/scripts/perms
--- a/scripts/perms
+++ b/scripts/perms
@@ -1,9 +1,14 @@
 #!/usr/bin/env bash
 
-# TODO: Make it print out permissions of the given files in octal format
-#
-# E.g.:
-# $ perms weather ../README.md
-# 775 weather
-# 664 ../README.md
+if [[ $# -eq 0 ]]; then
+    echo "Usage: $0 <file1> <file2> ..."
+    exit 1
+fi
+
+for file in "$@"; do
+    [[ -e "$file" ]] || { echo "File not found: $file"; continue; }
+    perms=$(stat -c "%a" "$file")
+    echo "$perms $file"
+done
+
 
